version: '3.5'

#Para rodar a aplicação react pelo docker
#docker run --rm -v $(pwd):/projeto -w /projeto node:10-slim npm install
#docker run --rm -v $(pwd):/projeto -p 3000:3000 -w /projeto node:10-slim npm start

#para roder os services abaixo
#docker-compose up -d

#para terminar os services abaixo
#docker-compose down 

services:

#docker exec -it forum_redis_cache redis-cli monitor
  redis:
    image: redis:3.0.6
    restart: always
    container_name: forum_redis_cache
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
          
  #spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
  db:
    image: mariadb:10.3
    container_name: forum_maria_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: fj27_spring
      MYSQL_USER: spring
      MYSQL_PASSWORD: pass  
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  adminer:
    image: adminer
    container_name: forum_adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

networks:     
  backend:
    driver: bridge
    name: fj27_network
    