management:
  endpoint:
    health:
      show-details: always
#data
spring:
  profiles: "prod"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fj27_spring?createDatabaseIfNotExist=true
    username: root
    password: pass
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
        hibernate.format_sql: false
        hibernate.show_sql: true  
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: fj27.spring@gmail.com
    password: ozlwonkcofjwllms
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  
        
# jwt info
alura:
  forum:
    jwt:
      secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
      expiration: 604800000
      
---

#data
spring:
  profiles:
    active: "dev"
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fj27_spring?createDatabaseIfNotExist=true
    username: root
    password: pass
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
        hibernate.format_sql: false
        hibernate.show_sql: true  
        
  mail:
    protocol: smtp
    host: localhost
    port: 3025
    username: fj27.spring@gmail.com
    password: 123456
  
        
# jwt info
alura:
  forum:
    jwt:
      secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
      expiration: 604800000

---

spring:
  profiles: "test"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fj27_spring_test?createDatabaseIfNotExist=true
    username: root
    password: pass
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
        hibernate.format_sql: false
        hibernate.show_sql: true  
        
  mail:
    protocol: smtp
    host: localhost
    port: 3025
    username: fj27.spring@gmail.com
    password: 123456
      
#server:
#  servlet:
#    context-path: /v1